import { useState } from "react";
import { PageHeader } from "../components/ui";

// ---------------------------------------------------------------------------
// Interactive architecture map. Each node carries accurate facts about the
// CURRENT system (two-Job split, 12-hourly Data Setup, real medallion counts,
// Lakebase reverse-ETL, governed FMAPI). Clicking/hovering a node shows its
// detail in the sticky side panel. Pure CSS/React — theme-aware, no new deps.
// ---------------------------------------------------------------------------

interface Node {
  id: string;
  label: string;
  sub?: string;
  ico: string;
  tag: string;
  desc: string;
  facts: string[];
}

interface Layer {
  title: string;
  sub: string;
  accent: string; // CSS color for the layer's left rail
  nodes: Node[];
}

const LAYERS: Layer[] = [
  {
    title: "Ingest",
    sub: "raw shipping data + documents",
    accent: "var(--accent-3)",
    nodes: [
      {
        id: "raw",
        label: "Raw Volume",
        sub: "JSONL per entity",
        ico: "🗄️",
        tag: "Bronze source",
        desc: "Deterministic synthetic data for a coherent container-liner business is landed as newline-delimited JSON in a Unity Catalog Volume — a realistic customer landing zone.",
        facts: [
          "Generated by pil_workshop.datagen (seed = 42 → reproducible)",
          "Vessels, ports (real UN/LOCODEs), routes, voyages, bookings, events, invoices, spare parts",
          "Deliberately messy on landing: nulls, dupes, bad port codes",
        ],
      },
      {
        id: "docs",
        label: "Documents",
        sub: "invoice PDFs · container images",
        ico: "📄",
        tag: "Unstructured",
        desc: "Freight-invoice PDFs (reportlab) and labelled container images (Pillow) feed the two AI agents. Invoice numbers/dates are anchored to a fixed date so documents are byte-stable across runs.",
        facts: [
          "PDFs → bronze/raw_invoices volume",
          "Images → bronze/container_images volume",
          "~10% carry a planted anomaly (total mismatch / missing PO / duplicate no)",
        ],
      },
    ],
  },
  {
    title: "Medallion",
    sub: "Bronze → Silver → Gold on Unity Catalog",
    accent: "var(--accent)",
    nodes: [
      {
        id: "bronze",
        label: "Bronze",
        sub: "raw Delta",
        ico: "🥉",
        tag: "Layer 1 · raw",
        desc: "The landed files registered as Delta tables, intentionally messy — so the Silver step has real cleaning work to demonstrate.",
        facts: [
          "1:1 with the raw entities",
          "Nulls, duplicate keys, mixed date formats, negative dwell",
          "CREATE OR REPLACE — safe to re-run",
        ],
      },
      {
        id: "silver",
        label: "Silver",
        sub: "17 clean tables",
        ico: "🥈",
        tag: "Layer 2 · clean",
        desc: "Cleaned, conformed, documented tables with primary/foreign keys and column comments — the trustworthy core the whole app and analytics read from.",
        facts: [
          "17 tables incl. invoice_extractions & container_inspections",
          "Constraints + PK/FK + column comments",
          "Injected messiness resolved here",
        ],
      },
      {
        id: "gold",
        label: "Gold",
        sub: "MVs · metric views · analytics",
        ico: "🥇",
        tag: "Layer 3 · business",
        desc: "Business-ready surfaces tuned to PIL's KPIs: materialized views, governed metric views, AI-usage views, and the analytics views behind the Genie Code dashboards.",
        facts: [
          "4 materialized views + 9 metric views (YAML)",
          "3 AI-usage views + 3 analytics views",
          "4 gold tables incl. invoice_exceptions & the synced decisions",
        ],
      },
    ],
  },
  {
    title: "Governed AI",
    sub: "Unity AI Gateway → Foundation Model APIs",
    accent: "var(--accent-2)",
    nodes: [
      {
        id: "invoice-agent",
        label: "Invoice Agent",
        sub: "parse · extract · reconcile",
        ico: "🧾",
        tag: "Text pipeline",
        desc: "Uploaded PDFs are parsed (ai_parse_document), fields + line items extracted (ai_extract + ai_query), and reconciled against ground truth into gold.invoice_exceptions.",
        facts: [
          "Flat header fields via ai_extract; nested line-items via ai_query",
          "Exceptions: total_mismatch · missing_po · duplicate_no",
          "Shares one governed text endpoint with the notebooks",
        ],
      },
      {
        id: "vision-agent",
        label: "Container Vision",
        sub: "damage classification",
        ico: "📦",
        tag: "Vision pipeline",
        desc: "Multimodal vision classifies each container image as none / minor / major damage with a confidence and a recommended action, scored against ground-truth labels.",
        facts: [
          "Python llm.chat multimodal path (robust vs SQL ai_query on serverless)",
          "Confidence + recommended action + reasoning",
          "Accuracy tracked vs labelled ground truth",
        ],
      },
      {
        id: "gateway",
        label: "Unity AI Gateway",
        sub: "rate-limit · usage-track",
        ico: "🛡️",
        tag: "Governance",
        desc: "Every model call — notebooks and app alike — routes through the same governed FMAPI endpoints. No external providers, no keys. Usage flows to the gold usage views and Dashboard Page 4.",
        facts: [
          "Endpoint names live only in src/pil_workshop/llm.py",
          "Per-user rate limits + usage tracking enabled per endpoint",
          "Sourced from system.serving.endpoint_usage",
        ],
      },
    ],
  },
  {
    title: "Consume & Serve",
    sub: "this app, analytics, and ML",
    accent: "var(--accent-3)",
    nodes: [
      {
        id: "app",
        label: "This App",
        sub: "React + FastAPI + Lakebase",
        ico: "🚢",
        tag: "Databricks App",
        desc: "A React + Vite UI over a FastAPI backend. It closes the loop: analytical exceptions → Lakebase review queue → human decision → back to the gold layer.",
        facts: [
          "Lakebase (Postgres): review queue · decisions · work orders",
          "Reverse-ETL → gold.invoice_decisions_synced",
          "Runs as its service principal — no PATs anywhere",
        ],
      },
      {
        id: "analytics",
        label: "Analytics",
        sub: "Dashboard · Genie · Genie Code",
        ico: "📊",
        tag: "AI/BI",
        desc: "A multi-page AI/BI dashboard, a Genie space (natural-language Q&A, also in Genie One), and a Genie Code build-your-own-dashboard lab — all over the gold layer.",
        facts: [
          "Dashboard with a daily 04:00 refresh schedule",
          "Genie space bound to 12 tables/views",
          "Page 4 shows governed AI usage",
        ],
      },
      {
        id: "ml",
        label: "ML",
        sub: "forecasting · optimization",
        ico: "🤖",
        tag: "MLflow + OR-Tools",
        desc: "Spare-parts / demand forecasting (Croston/TSB + a global LightGBM) evaluated with WAPE/MASE, and empty-container repositioning solved as a min-cost flow with OR-Tools.",
        facts: [
          "MLflow: nested runs, sweep, evaluate, UC registry, @champion",
          "Intermittent-demand methods for spare parts",
          "OR-Tools min-cost-flow repositioning plan",
        ],
      },
    ],
  },
];

const ORCHESTRATION: Node = {
  id: "jobs",
  label: "Orchestration",
  sub: "two Databricks Jobs",
  ico: "⚙️",
  tag: "Workflows",
  desc: "The pipeline runs as two serverless Databricks Jobs, created idempotently by name. Data Setup refreshes the medallion + agents + ML on a schedule; Consumables Setup deploys the dashboard, Genie, Lakebase and app once.",
  facts: [
    "PIL Workshop — Data Setup: 9 tasks, every 12 hours, appends an incremental slice",
    "PIL Workshop — Consumables Setup: 4 tasks, one-time",
    "Schedule created UNPAUSED so it runs on its cron immediately",
  ],
};

const TECH: { ico: string; label: string }[] = [
  { ico: "⚛️", label: "React + Vite + TypeScript" },
  { ico: "⚡", label: "FastAPI" },
  { ico: "🧱", label: "Unity Catalog" },
  { ico: "🐘", label: "Lakebase (Postgres)" },
  { ico: "🛡️", label: "Unity AI Gateway · FMAPI" },
  { ico: "📈", label: "MLflow" },
  { ico: "🧮", label: "OR-Tools" },
  { ico: "📊", label: "AI/BI + Genie" },
];

const CONCEPTS: { ico: string; title: string; desc: string }[] = [
  {
    ico: "🛡️",
    title: "Governed by design",
    desc: "Every LLM call — notebooks and app — goes through the same Unity-AI-Gateway FMAPI endpoints. Rate-limited, usage-tracked, audited; zero external providers or keys.",
  },
  {
    ico: "🔄",
    title: "Reverse-ETL loop",
    desc: "Analytical exceptions flow to a Lakebase operational queue, a human approves/rejects, and the decision syncs back to the gold layer — closing the analytics-to-action loop.",
  },
  {
    ico: "🏅",
    title: "Medallion architecture",
    desc: "Bronze (raw) → Silver (clean, documented) → Gold (business KPIs & views). One trustworthy core that the app, dashboards, Genie, and ML all read from.",
  },
  {
    ico: "♻️",
    title: "Idempotent & reproducible",
    desc: "Seeded synthetic data (seed=42) and CREATE-OR-REPLACE notebooks mean every run is identical and safe to repeat — the whole workshop rebuilds cleanly from scratch.",
  },
];

export function About() {
  const [activeId, setActiveId] = useState<string>("silver");

  const allNodes = [...LAYERS.flatMap((l) => l.nodes), ORCHESTRATION];
  const active = allNodes.find((n) => n.id === activeId) ?? null;

  return (
    <>
      <PageHeader
        title="About this app"
        subtitle="The end-to-end architecture you built in the workshop — click any node to explore it."
      />

      <div className="arch">
        {/* Left: the layered, interactive flow */}
        <div className="arch-flow">
          {LAYERS.map((layer, i) => (
            <div key={layer.title}>
              <section
                className="arch-layer"
                style={{ ["--layer-accent" as string]: layer.accent }}
              >
                <div className="arch-layer-head">
                  <span className="arch-layer-title">{layer.title}</span>
                  <span className="arch-layer-sub">{layer.sub}</span>
                </div>
                <div className="arch-nodes">
                  {layer.nodes.map((n) => (
                    <ArchNode
                      key={n.id}
                      node={n}
                      active={activeId === n.id}
                      onSelect={setActiveId}
                    />
                  ))}
                </div>
              </section>
              {i < LAYERS.length - 1 && <div className="arch-connector" aria-hidden="true" />}
            </div>
          ))}

          {/* Orchestration sits alongside as the thing that drives it all */}
          <div className="arch-connector" aria-hidden="true" />
          <section
            className="arch-layer"
            style={{ ["--layer-accent" as string]: "var(--brand)" }}
          >
            <div className="arch-layer-head">
              <span className="arch-layer-title">Orchestration</span>
              <span className="arch-layer-sub">what drives the whole pipeline</span>
            </div>
            <div className="arch-nodes">
              <ArchNode node={ORCHESTRATION} active={activeId === "jobs"} onSelect={setActiveId} />
            </div>
          </section>
        </div>

        {/* Right: sticky detail panel */}
        <aside className="arch-detail enter" key={activeId}>
          {active ? (
            <>
              <div className="arch-detail-ico">{active.ico}</div>
              <h2 className="arch-detail-title">{active.label}</h2>
              <span className="arch-detail-tag">{active.tag}</span>
              <p className="arch-detail-desc">{active.desc}</p>
              <ul className="arch-detail-facts">
                {active.facts.map((f, i) => (
                  <li key={i}>{f}</li>
                ))}
              </ul>
            </>
          ) : (
            <p className="arch-detail-hint">Select a node to see how it works.</p>
          )}
        </aside>
      </div>

      {/* Tech stack */}
      <div className="card" style={{ marginTop: 20 }}>
        <h2 className="section-title">Built with</h2>
        <div className="tech-strip">
          {TECH.map((t) => (
            <span key={t.label} className="tech-chip">
              <span className="tech-ico">{t.ico}</span>
              {t.label}
            </span>
          ))}
        </div>
      </div>

      {/* Key concepts */}
      <h2 className="section-title" style={{ marginTop: 24, marginBottom: 4 }}>
        Key ideas
      </h2>
      <div className="concept-grid">
        {CONCEPTS.map((c) => (
          <div key={c.title} className="concept-card">
            <div className="concept-ico">{c.ico}</div>
            <h3 className="concept-title">{c.title}</h3>
            <p className="concept-desc">{c.desc}</p>
          </div>
        ))}
      </div>
    </>
  );
}

function ArchNode({
  node,
  active,
  onSelect,
}: {
  node: Node;
  active: boolean;
  onSelect: (id: string) => void;
}) {
  return (
    <button
      type="button"
      className={`arch-node${active ? " active" : ""}`}
      onClick={() => onSelect(node.id)}
      onFocus={() => onSelect(node.id)}
      aria-pressed={active}
    >
      <span className="arch-node-ico">{node.ico}</span>
      <span>
        {node.label}
        {node.sub && <span className="arch-node-sub"> · {node.sub}</span>}
      </span>
    </button>
  );
}
